fix: version var

diff --git a/workflow/Jenkinsfile b/workflow/Jenkinsfile
--- a/workflow/Jenkinsfile
+++ b/workflow/Jenkinsfile
@@ -149,8 +149,13 @@ stage('Semantic Release (dry-run)') {
 
                 cat semantic.log
 
-                VERSION=$(grep -oE '[0-9]+\.[0-9]+\.[0-9]+' sr.log | tail -1)
-                [ -z "$VERSION" ] && exit 1
+                VERSION=$(grep 'next release version is' sr.log | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | tail -1)
+
+                [ -z "$VERSION" ] && {
+                  echo "Unable to detect semantic-release version"
+                  exit 1
+                }
+
                 echo "VERSION=$VERSION" > version.env
                 echo "Next version: $VERSION"
               '''
