fix: update job commit&tag

diff --git a/cap/Jenkinsfile b/cap/Jenkinsfile
--- a/cap/Jenkinsfile
+++ b/cap/Jenkinsfile
@@ -520,66 +520,88 @@ pipeline {
    }
  }
 
-    /* =========================================================
+     /* =========================================================
      * COMMIT & TAG
      * ========================================================= */
     stage('Commit & Tag') {
 
-      agent {
-        kubernetes(k8sAgent(
-          cloud: 'kubernetes',
-          podTemplate: 'gh',
-          serviceAccount: 'jenkins'
-        ))
-      }
+  agent {
+    kubernetes(k8sAgent(
+      cloud: 'kubernetes',
+      podTemplate: 'gh',
+      serviceAccount: 'jenkins'
+    ))
+  }
 
-      steps {
+  steps {
 
-        container('gh') {
+    container('gh') {
 
-          unstash 'updated-source'
-          unstash 'version'
+      unstash 'updated-source'
+      unstash 'version'
 
-          withCredentials([
-            usernamePassword(
-              credentialsId: 'github-token',
-              usernameVariable: 'GIT_USER',
-              passwordVariable: 'GIT_TOKEN'
-            )
-          ]) {
+      withAwsSecret([
+        secret_id: "SM-AUT-PLAT-PROD-SAP-BTP-GH-TOKEN".toUpperCase(),
+        type: "keyvalue"
+      ]) {
 
-            dir("${env.REPOSITORY_NAME}") {
+        script {
 
-              sh '''
-                set -e
+          def githubToken = env.token
+          def targetRepo = "sap-btp-wflibero2-cap-cicd"
 
-                VERSION=$(cat version.env | sed 's/VERSION=//')
+          sh """
+  set -e
 
-                git config user.email "ci@jenkins"
-                git config user.name "Jenkins CI"
+  VERSION=\$(grep 'VERSION=' ${WORKSPACE}/${REPOSITORY_NAME}/version.env | cut -d '=' -f2)
 
-                git remote set-url origin \
-                  https://${GIT_USER}:${GIT_TOKEN}@github.com/KPICorporate/${REPOSITORY_NAME}.git
+  if [ -z "\$VERSION" ]; then
+    echo "ERROR: VERSION is empty"
+    exit 1
+  fi
 
-                git fetch --all --tags
+  echo "Using VERSION: \$VERSION"
 
-                git checkout main
+  TARGET_REPO="sap-btp-wflibero2-cap-cicd"
+  TARGET_DIR="/tmp/\$TARGET_REPO"
 
-                git pull origin main
+  echo "Target dir: \$TARGET_DIR"
 
-                git add cap/package.json
-                git add cap/package-lock.json
-                git add cap/mta.yaml
+  git config --global user.email "ci@jenkins"
+  git config --global user.name "Jenkins CI"
 
-                git commit \
-                  -m "chore(release): ${VERSION} [skip ci]" \
-                  || true
+  echo "Cloning repo..."
 
-                git tag -f "v${VERSION}"
+  rm -rf "\$TARGET_DIR"
 
-                git push origin main
-                git push origin --tags --force
-              '''
+  git clone https://x-access-token:${githubToken}@github.com/KPICorporate/\$TARGET_REPO.git "\$TARGET_DIR"
+
+  if [ ! -d "\$TARGET_DIR/.git" ]; then
+    echo "ERROR: clone failed"
+    exit 1
+  fi
+
+  cd "\$TARGET_DIR"
+
+  echo "Copy files"
+
+  cp -f ${WORKSPACE}/${REPOSITORY_NAME}/cap/mta.yaml mta.yaml
+  cp -f ${WORKSPACE}/${REPOSITORY_NAME}/cap/package.json package.json
+  cp -f ${WORKSPACE}/${REPOSITORY_NAME}/cap/package-lock.json package-lock.json
+
+  git add \
+  mta.yaml \
+  package.json \
+  package-lock.json
+
+
+  git commit -m "chore(release): \$VERSION [skip ci]" || true
+
+  git tag -f "v\$VERSION"
+
+  git push origin main
+  git push origin --tags --force
+"""
             }
           }
         }
